export default {
  id: "bobide",
  priority: 30,
  hasFree: true,
  alias: "bob",
  uiAlias: "bob",
  aliases: ["bob-ide", "ibm-bob"],
  display: {
    name: "IBM Bob IDE",
    icon: "smart_toy",
    color: "#0f62fe",
    textIcon: "BOB",
    website: "https://ibm.com/bob",
    notice: {
      text: "Free tier models on IBM Bob including IBM Granite Code, Codestral, OpenAI, Claude & Gemini models.",
      apiKeyUrl: "https://ibm.com/bob/settings/keys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.bob-ide.ibm.com/v1/chat/completions",
    thinkingFormat: "openai",
    quirks: {
      skipJailbreakInject: true,
      preserveReasoningContent: true,
    },
  },
  models: [
    {
      id: "granite-code-3b",
      name: "IBM Granite Code (3B)",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Siêu nhỏ nhẹ, tối ưu cho auto-complete.",
    },
    {
      id: "granite-code-8b",
      name: "IBM Granite Code (8B)",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Cân bằng cho giải thích code.",
    },
    {
      id: "granite-code-20b",
      name: "IBM Granite Code (20B)",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Quét lỗi bảo mật.",
    },
    {
      id: "granite-code-34b",
      name: "IBM Granite Code (34B)",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Viết các cấu trúc hàm ngắn.",
    },
    {
      id: "codestral-22b",
      name: "Mistral Codestral 22B",
      contextLength: 32768,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Đối tác mã nguồn mở phục vụ tác vụ phổ thông ngoài hệ sinh thái IBM i.",
    },
    {
      id: "mistral-7b",
      name: "Mistral 7B Instruct",
      contextLength: 32768,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mã nguồn mở phục vụ tác vụ phổ thông ngoài hệ sinh thái IBM i.",
    },
    {
      id: "o3",
      name: "OpenAI o3",
      contextLength: 200000,
      maxOutputTokens: 100000,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình lý luận thế hệ mới nhất của OpenAI, xử lý các thuật toán và logic lập trình chuyên sâu.",
    },
    {
      id: "claude-4-opus",
      name: "Claude 4 Opus",
      contextLength: 200000,
      maxOutputTokens: 64000,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình mạnh mẽ nhất của Anthropic, hiểu ngữ cảnh dự án lớn và viết code với độ chính xác tuyệt đối.",
    },
    {
      id: "claude-3-5-sonnet",
      name: "Claude 3.5 Sonnet",
      contextLength: 200000,
      maxOutputTokens: 8192,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình có tốc độ và độ thông minh cân bằng nhất, thường xuyên được Bob gọi để xử lý các tác vụ code hàng ngày.",
    },
    {
      id: "gpt-4o",
      name: "GPT-4o",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình đa phương thức (xử lý cả văn bản, hình ảnh, tài liệu cấu trúc) với tốc độ phản hồi cực nhanh từ OpenAI.",
    },
    {
      id: "gpt-4o-mini",
      name: "GPT-4o mini",
      contextLength: 128000,
      maxOutputTokens: 16384,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Bản rút gọn siêu tốc của OpenAI, xử lý văn bản cực kỳ tiết kiệm token.",
    },
    {
      id: "claude-3-5-haiku",
      name: "Claude 3.5 Haiku",
      contextLength: 200000,
      maxOutputTokens: 8192,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình gọn nhẹ thế hệ mới của Anthropic, tối ưu chi phí nhưng vẫn giữ tư duy logic rất tốt.",
    },
    {
      id: "claude-3-haiku",
      name: "Claude 3 Haiku",
      contextLength: 200000,
      maxOutputTokens: 4096,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Phiên bản Haiku đời đầu, xử lý phản hồi nhanh và tốn rất ít tài nguyên.",
    },
    {
      id: "gemini-1.5-flash",
      name: "Gemini 1.5 Flash",
      contextLength: 1000000,
      maxOutputTokens: 8192,
      supportsTools: true,
      supportsStreaming: true,
      isFree: true,
      description: "Mô hình từ Google với khả năng đọc và xử lý các tệp tài liệu hoặc mã nguồn có độ dài lớn (Context Window rộng) với chi phí thấp.",
    },
  ],
  serviceKinds: ["llm"],
  passthroughModels: true,
};
