export default {
  id: "bobide",
  priority: 30,
  hasFree: true,
  alias: "bob",
  uiAlias: "bob",
  aliases: ["bob-ide", "ibm-bob"],
  display: {
    name: "IBM Bob IDE",
    icon: "smart_toy",
    color: "#0f62fe",
    textIcon: "BOB",
    website: "https://bob.ibm.com",
    notice: {
      text: "IBM Bob Production API — Hỗ trợ đầy đủ các model Premium (Claude Sonnet 4.6), Ultra (Opus 4.8), Fast (Haiku 4.5), GPT-5.4, Gemini 3.5/3.7 và IBM Granite Code.",
      apiKeyUrl: "https://bob.ibm.com/admin/apikeys",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.us-east.bob.ibm.com/inference/v1/chat/completions",
    validateUrl: "https://api.us-east.bob.ibm.com/inference/v1/model/info",
    auth: { combined: true, header: "Authorization", scheme: "apikey" },
    headers: {
      "User-Agent": "bobshell/2.0.0",
    },
    thinkingFormat: "openai",
    quirks: {
      skipJailbreakInject: true,
      preserveReasoningContent: true,
    },
  },
  models: [
    // Live Native IBM Bob Models
    { id: "premium", name: "Bob Premium (Claude Sonnet 4.5/4.6)", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Claude Sonnet 4.5/4.6 mạnh mẽ cho các tác vụ lập trình phức tạp." },
    { id: "premium-ide", name: "Bob Premium IDE (Claude Sonnet 4.6)", contextLength: 270000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Claude Sonnet 4.6 tối ưu hóa cho IDE workflow." },
    { id: "premium-shell", name: "Bob Premium Shell", contextLength: 270000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Claude Sonnet 4.6 tối ưu cho terminal & CLI." },
    { id: "sonnet-4.5", name: "Claude Sonnet 4.5", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Claude Sonnet 4.5 native trên IBM Bob." },
    { id: "fast", name: "Bob Fast (Claude Haiku 4.5)", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Claude Haiku 4.5 phản hồi siêu tốc." },
    { id: "explorer", name: "Bob Explorer", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "Bob Explorer." },
    { id: "wxO-model", name: "IBM watsonx.ai Orchestrator", contextLength: 1000000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, supportsVision: true, isFree: true, description: "watsonx.ai Orchestrator model với context window 1,000,000 token." },
    { id: "granite-8b-code-instruct", name: "IBM Granite Code 8B", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mô hình IBM Granite Code 8B tối ưu cho giải thích code & SQL/DB2." },
    { id: "gpt-oss-20b", name: "GPT OSS 20B", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Mô hình mã nguồn mở 20B tốc độ cao với khả năng reasoning." },
    { id: "openai/gpt-oss-20b", name: "OpenAI GPT OSS 20B", upstreamModelId: "gpt-oss-20b", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true },

    // Aliases mapped to live models to prevent 404
    { id: "ultra", name: "Bob Ultra (Claude Opus 4.8)", upstreamModelId: "premium", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Claude Opus/Sonnet xử lý tác vụ tư duy kiến trúc và dự án lớn." },
    { id: "gpt-2026-5.4", name: "Bob GPT-5.4", upstreamModelId: "gpt-oss-20b", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, isFree: true, description: "OpenAI-compatible reasoning model trên Bob." },
    { id: "gpt-2026-5.4-bobv2", name: "Bob GPT-5.4 v2", upstreamModelId: "gpt-oss-20b", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, isFree: true },
    { id: "gemini-3.5-flash", name: "Bob Gemini 3.5 Flash", upstreamModelId: "wxO-model", contextLength: 1000000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Context lớn 1M tokens." },
    { id: "gemini-3.7-flash-medium", name: "Bob Gemini 3.7 Flash Medium", upstreamModelId: "wxO-model", contextLength: 1000000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true },
    { id: "sonnet-4.6", name: "Claude Sonnet 4.6", upstreamModelId: "premium-ide", contextLength: 270000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true },
    { id: "sonnet-5", name: "Claude Sonnet 5", upstreamModelId: "premium", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true },
    { id: "haiku-4.5", name: "Claude Haiku 4.5", upstreamModelId: "fast", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true },

    // Free Tier Orchestration Mappings
    { id: "granite-code-3b", name: "IBM Granite Code (3B)", upstreamModelId: "granite-8b-code-instruct", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Siêu nhỏ nhẹ, tối ưu cho auto-complete." },
    { id: "granite-code-8b", name: "IBM Granite Code (8B)", upstreamModelId: "granite-8b-code-instruct", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Cân bằng cho giải thích code." },
    { id: "granite-code-20b", name: "IBM Granite Code (20B)", upstreamModelId: "granite-8b-code-instruct", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Quét lỗi bảo mật." },
    { id: "granite-code-34b", name: "IBM Granite Code (34B)", upstreamModelId: "granite-8b-code-instruct", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Viết các cấu trúc hàm ngắn." },
    { id: "codestral-22b", name: "Mistral Codestral 22B", upstreamModelId: "fast", contextLength: 32768, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Đối tác mã nguồn mở phục vụ tác vụ phổ thông ngoài hệ sinh thái IBM i." },
    { id: "mistral-7b", name: "Mistral 7B Instruct", upstreamModelId: "fast", contextLength: 32768, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mã nguồn mở phục vụ tác vụ phổ thông ngoài hệ sinh thái IBM i." },
    { id: "o3", name: "OpenAI o3", upstreamModelId: "gpt-oss-20b", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Mô hình lý luận với reasoning, xử lý các thuật toán và logic lập trình chuyên sâu." },
    { id: "claude-4-opus", name: "Claude 4 Opus", upstreamModelId: "premium", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mô hình mạnh mẽ của Anthropic, hiểu ngữ cảnh dự án lớn và viết code với độ chính xác cao." },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet", upstreamModelId: "premium", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mô hình có tốc độ và độ thông minh cân bằng nhất, xử lý các tác vụ code hàng ngày." },
    { id: "gpt-4o", name: "GPT-4o", upstreamModelId: "gpt-oss-20b", contextLength: 131072, maxOutputTokens: 131072, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mô hình đa dụng tốc độ cao từ OpenAI-compatible ecosystem." },
    { id: "gpt-4o-mini", name: "GPT-4o mini", upstreamModelId: "fast", contextLength: 128000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Bản rút gọn siêu tốc, xử lý văn bản cực kỳ tiết kiệm token." },
    { id: "claude-3-5-haiku", name: "Claude 3.5 Haiku", upstreamModelId: "fast", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Mô hình gọn nhẹ thế hệ mới của Anthropic, tối ưu chi phí nhưng vẫn giữ tư duy logic rất tốt." },
    { id: "claude-3-haiku", name: "Claude 3 Haiku", upstreamModelId: "fast", contextLength: 200000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Phiên bản Haiku, xử lý phản hồi nhanh và tốn rất ít tài nguyên." },
    { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash", upstreamModelId: "wxO-model", contextLength: 1000000, maxOutputTokens: 64000, supportsTools: true, supportsStreaming: true, isFree: true, description: "Khả năng đọc và xử lý các tệp tài liệu hoặc mã nguồn context lớn (1,000,000 token)." },
  ],
  serviceKinds: ["llm"],
  passthroughModels: true,
};
