export default {
  id: "freebuff",
  priority: 21,
  hasFree: true,
  alias: "fb",
  aliases: [
    "freebuff-cli",
    "freebuff-ai",
    "codebuff",
  ],
  uiAlias: "fb",
  display: {
    name: "Freebuff",
    icon: "terminal",
    color: "#54A967",
    textIcon: "FB",
    website: "https://freebuff.com",
    notice: {
      text: "Freebuff CLI: 100% free coding agent for terminal, desktop & web, funded by ads. Install via: npm i -g freebuff.",
      apiKeyUrl: "https://freebuff.com",
      signupUrl: "https://freebuff.com/cli",
    },
  },
  category: "freeTier",
  authType: "oauth",
  hasOAuth: true,
  authModes: [
    "oauth",
    "apikey",
  ],
  authHint: "Freebuff Auth Token or Browser Login",
  transport: {
    baseUrl: "https://www.codebuff.com/api/v1/chat/completions",
    validateUrl: "https://www.codebuff.com/api/v1/me?fields=id,email",
    thinkingFormat: "openai",
  },
  oauth: {
    loginCodeUrl: "https://freebuff.com/api/auth/cli/code",
    loginStatusUrl: "https://freebuff.com/api/auth/cli/status",
    sessionUrl: "https://www.codebuff.com/api/v1/freebuff/session",
    meUrl: "https://www.codebuff.com/api/v1/me",
    usageUrl: "https://www.codebuff.com/api/v1/usage",
    localConfigPath: "~/.config/manicode/credentials.json",
  },
  models: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", contextLength: 1048576, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Default model on Freebuff CLI, Desktop, Web & Cloud. Smart & fast." },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash", contextLength: 131072, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Deep reasoning model on Freebuff." },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", contextLength: 272000, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Strong all-around OpenAI model on Freebuff." },
    { id: "mimo-2.5", name: "MiMo 2.5", contextLength: 131072, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Balanced model for everyday coding tasks." },
    { id: "solar-pro-4", name: "Solar Pro 4", contextLength: 65536, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "Upstage Solar Pro 4 model." },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite", contextLength: 1048576, maxOutputTokens: 65536, supportsTools: true, supportsStreaming: true, isFree: true, description: "Specialist model for file finding, search and research tasks." },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", contextLength: 1048576, maxOutputTokens: 65536, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true, description: "Google Gemini 3.8 Flash model on Freebuff." },
    { id: "minimax-m3", name: "MiniMax M3", contextLength: 131072, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true, description: "MiniMax M3 model on Freebuff." },
    { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 07/31", upstreamModelId: "deepseek-v4-flash", contextLength: 1048576, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, supportsReasoning: true, isFree: true },
    { id: "mimo-v2.5", name: "MiMo v2.5", upstreamModelId: "mimo-2.5", contextLength: 131072, maxOutputTokens: 16384, supportsTools: true, supportsStreaming: true, isFree: true },
  ],
  passthroughModels: true,
  serviceKinds: [
    "llm",
  ],
};
