export default {
  id: "genspark",
  priority: 45,
  hasFree: true,
  alias: "genspark",
  aliases: ["gsk"],
  uiAlias: "genspark",
  display: {
    name: "Genspark",
    icon: "auto_awesome",
    color: "#4F46E5",
    textIcon: "GSK",
    website: "https://www.genspark.ai",
    notice: {
      text: "Genspark Official LLM Proxy & Multi-Modal Generation (Image, Video, Audio)",
      apiKeyUrl: "https://www.genspark.ai",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://www.genspark.ai/api/llm_proxy/v1/chat/completions",
    validateUrl: "https://www.genspark.ai/api/tool_cli/me",
    format: "openai",
    auth: { combined: true, header: "Authorization", scheme: "bearer", hooks: ["gensparkHeaders"] },
    headers: {
      "X-GSK-CLI-Caps": "cli-groups-v2,cli-paths-v3,cli-actions-v4",
      "X-GSK-CLI-Version": "1.7.1",
    },
  },
  serviceKinds: ["llm", "image", "video"],
  imageConfig: {
    baseUrl: "https://www.genspark.ai/api/tool_cli/image_generation",
  },
  videoConfig: {
    baseUrl: "https://www.genspark.ai/api/tool_cli/video_generation",
    pollUrl: "https://www.genspark.ai/api/tool_cli/task_status",
  },
  models: [
    // ── LLM / Chat Models (Verified from Genspark OpenCode Config) ─
    { id: "claude-fable-5", name: "Claude Fable 5", kind: "llm" },
    { id: "claude-opus-5", name: "Claude Opus 5", kind: "llm" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8", kind: "llm" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7", kind: "llm" },
    { id: "claude-opus-4-6-1m", name: "Claude Opus 4.6 (1M context)", kind: "llm" },
    { id: "claude-sonnet-4-6-1m", name: "Claude Sonnet 4.6 (1M context)", kind: "llm" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6", kind: "llm" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", kind: "llm" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", kind: "llm" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", kind: "llm" },
    { id: "gpt-5.2", name: "GPT-5.2", kind: "llm" },
    { id: "gpt-5.4", name: "GPT-5.4", kind: "llm" },
    { id: "gpt-5.5", name: "GPT-5.5", kind: "llm" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", kind: "llm" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", kind: "llm" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna", kind: "llm" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", kind: "llm" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano", kind: "llm" },
    { id: "deep-seek-v4-pro", name: "DeepSeek V4 Pro", kind: "llm" },
    { id: "deep-seek-v4-flash", name: "DeepSeek V4 Flash", kind: "llm" },
    { id: "grok-4.5", name: "Grok 4.5", kind: "llm" },
    { id: "grok-4.6", name: "Grok 4.6", kind: "llm" },
    { id: "kimi-k2p6", name: "Kimi K2.6", kind: "llm" },
    { id: "minimax-m2p7", name: "MiniMax M2.7", kind: "llm" },
    { id: "minimax-m3", name: "MiniMax M3", kind: "llm" },
    { id: "glm-5p2", name: "GLM-5.2", kind: "llm" },
    { id: "kimi-k3", name: "Kimi K3", kind: "llm" },
    { id: "deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813", kind: "llm" },
    { id: "solar-pro4", name: "Solar Pro 4", kind: "llm" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro", kind: "llm" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash", kind: "llm" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", kind: "llm" },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", kind: "llm" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", kind: "llm" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite", kind: "llm" },

    // ── Image Generation Models (Verified from Genspark Tool CLI) ─
    { id: "nano-banana-pro", name: "Gemini Nano Banana Pro", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "nano-banana-2", name: "Gemini Nano Banana 2", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "nano-banana-2-flash-lite", name: "Gemini Nano Banana 2 Flash Lite", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "gpt-image-2", name: "GPT Image 2", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "fal-ai/bytedance/seedream/v5/pro", name: "ByteDance Seedream v5 Pro", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "fal-ai/bytedance/seedream/v5/lite", name: "ByteDance Seedream v5 Lite", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "xai/grok-imagine-image", name: "xAI Grok Imagine Image 2.0", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "qwen-image-3", name: "Qwen Image 3", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "fal-ai/flux-2-pro", name: "FLUX 2 Pro", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "fal-ai/z-image/turbo", name: "Z-Image Turbo", kind: "image", params: ["prompt", "image_urls", "aspect_ratio", "image_size"] },
    { id: "bbox-segment", name: "BBox Segment", kind: "image", params: ["prompt", "image_urls", "bbox"] },
    { id: "fal-bria-rmbg", name: "BRIA Background Removal", kind: "image", params: ["image_urls"] },
    { id: "fal-ai/recraft-clarity-upscale", name: "Recraft Clarity Upscale", kind: "image", params: ["image_urls"] },
    { id: "fal-ai/image-editing/text-removal", name: "Text & Watermark Removal", kind: "image", params: ["image_urls"] },
    { id: "flux-pro/outpaint", name: "FLUX Pro Outpaint", kind: "image", params: ["image_urls", "aspect_ratio"] },

    // ── Video Generation Models (18 models) ────────────────────
    { id: "kling/v3", name: "Kling V3", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "audio_enable", "tier"] },
    { id: "kling/o3", name: "Kling O3", kind: "video", params: ["prompt", "image_urls", "video_url", "aspect_ratio", "duration", "audio_enable", "tier"] },
    { id: "gemini/veo3.1", name: "Gemini Veo 3.1", kind: "video", params: ["prompt", "image_urls", "video_url", "aspect_ratio", "duration", "tier", "video_size"] },
    { id: "minimax/h3", name: "MiniMax H3 (2K)", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "wan/v2.7", name: "Wan v2.7", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "vidu/q3", name: "Vidu Q3", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "tier", "video_size"] },
    { id: "runway/gen4_turbo", name: "Runway Gen-4 Turbo", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration"] },
    { id: "pixverse/v6", name: "PixVerse V6", kind: "video", params: ["prompt", "image_urls", "video_url", "aspect_ratio", "duration"] },
    { id: "pixverse/c1", name: "PixVerse C1", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "audio_enable", "video_size"] },
    { id: "fal-ai/bytedance/seedance-2.0", name: "ByteDance Seedance 2.0", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "tier", "video_size"] },
    { id: "fal-ai/bytedance-upscaler/upscale/video", name: "ByteDance Video Upscaler (2K)", kind: "video", params: ["video_url"] },
    { id: "xai/grok-imagine-video", name: "xAI Grok Imagine Video v1.5", kind: "video", params: ["prompt", "image_urls", "video_url", "aspect_ratio", "duration", "video_size"] },
    { id: "alibaba/happy-horse", name: "Alibaba Happy Horse", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "alibaba/happy-horse/reference-to-video", name: "Alibaba Happy Horse Ref2Video", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "alibaba/happy-horse/video-edit", name: "Alibaba Happy Horse Video Edit", kind: "video", params: ["prompt", "video_url", "image_urls"] },
    { id: "gemini/omni-flash", name: "Gemini Omni Flash", kind: "video", params: ["prompt", "image_urls", "video_url", "aspect_ratio", "duration", "video_size"] },
    { id: "bfl/flux-3-preview-high", name: "BFL FLUX 3 Video", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "fal-ai/bytedance/seedance-2.5", name: "ByteDance Seedance 2.5", kind: "video", params: ["prompt", "image_urls", "video_urls", "aspect_ratio", "duration", "video_size"] },
    { id: "wan/v3.0", name: "Alibaba Wan 3.0", kind: "video", params: ["prompt", "image_urls", "aspect_ratio", "duration", "tier", "video_size"] },
  ],
  passthroughModels: true,
};
