export default {
  id: "groq",
  priority: 60,
  hasFree: true,
  alias: "groq",
  display: {
    name: "Groq",
    icon: "speed",
    color: "#F55036",
    textIcon: "GQ",
    website: "https://groq.com",
    notice: {
      apiKeyUrl: "https://console.groq.com/keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.groq.com/openai/v1/chat/completions",
    validateUrl: "https://api.groq.com/openai/v1/models",
  },
  models: [
    { id: "qwen/qwen3.6-27b", name: "Qwen 3.6 27B", supportsTools: true, supportsVision: true, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B", supportsTools: true, supportsVision: false, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-20b", name: "GPT OSS 20B", supportsTools: true, supportsVision: false, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-safeguard-20b", name: "Safety GPT OSS 20B", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "allam-2-7b", name: "ALLaM-2 7B", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "groq/compound", name: "Groq Compound", supportsTools: true, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "groq/compound-mini", name: "Groq Compound Mini", supportsTools: true, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "meta-llama/llama-prompt-guard-2-86m", name: "Prompt Guard 2 86M", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "meta-llama/llama-prompt-guard-2-22m", name: "Prompt Guard 2 22M", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "whisper-large-v3", name: "Whisper Large v3", params: ["language","response_format","temperature","prompt"], kind: "stt", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "whisper-large-v3-turbo", name: "Whisper Large v3 Turbo", params: ["language","response_format","temperature","prompt"], kind: "stt", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
  ],
  serviceKinds: ["llm","imageToText","stt"],
  sttConfig: {
    baseUrl: "https://api.groq.com/openai/v1/audio/transcriptions",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
};
