export default {
  id: "groq",
  priority: 60,
  hasFree: true,
  alias: "groq",
  display: {
    name: "Groq",
    icon: "speed",
    color: "#F55036",
    textIcon: "GQ",
    website: "https://groq.com",
    notice: {
      apiKeyUrl: "https://console.groq.com/keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.groq.com/openai/v1/chat/completions",
    validateUrl: "https://api.groq.com/openai/v1/models",
  },
  models: [
    { id: "qwen/qwen3.8-27b", name: "Qwen 3.8 27B", contextLength: 131042, maxOutputTokens: 16384, supportsTools: true, supportsVision: true, supportsReasoning: true, supportsStreaming: true },
    { id: "qwen/qwen3.6-27b", name: "Qwen 3.6 27B", contextLength: 131072, maxOutputTokens: 16384, supportsTools: true, supportsVision: true, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B", contextLength: 131072, maxOutputTokens: 65536, supportsTools: true, supportsVision: false, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-20b", name: "GPT OSS 20B", contextLength: 131072, maxOutputTokens: 65536, supportsTools: true, supportsVision: false, supportsReasoning: true, supportsStreaming: true },
    { id: "openai/gpt-oss-safeguard-20b", name: "Safety GPT OSS 20B", contextLength: 131072, maxOutputTokens: 65536, supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "allam-2-7b", name: "ALLaM-2 7B", contextLength: 4096, maxOutputTokens: 4096, supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "groq/compound", name: "Groq Compound", contextLength: 131072, maxOutputTokens: 8192, supportsTools: true, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "groq/compound-mini", name: "Groq Compound Mini", contextLength: 131072, maxOutputTokens: 8192, supportsTools: true, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "meta-llama/llama-prompt-guard-2-86m", name: "Prompt Guard 2 86M", contextLength: 512, maxOutputTokens: 512, supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "meta-llama/llama-prompt-guard-2-22m", name: "Prompt Guard 2 22M", contextLength: 512, maxOutputTokens: 512, supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "canopylabs/orpheus-v1-english", name: "Orpheus v1 English", kind: "tts", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "canopylabs/orpheus-arabic-saudi", name: "Orpheus Arabic Saudi", kind: "tts", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: true },
    { id: "whisper-large-v3", name: "Whisper Large v3", params: ["language","response_format","temperature","prompt"], kind: "stt", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
    { id: "whisper-large-v3-turbo", name: "Whisper Large v3 Turbo", params: ["language","response_format","temperature","prompt"], kind: "stt", supportsTools: false, supportsVision: false, supportsReasoning: false, supportsStreaming: false },
  ],
  serviceKinds: ["llm","imageToText","stt","tts"],
  sttConfig: {
    baseUrl: "https://api.groq.com/openai/v1/audio/transcriptions",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
  ttsConfig: {
    baseUrl: "https://api.groq.com/openai/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    defaultModel: "canopylabs/orpheus-v1-english",
  },
};
