export default {
  id: "kilocode",
  priority: 70,
  alias: "kc",
  uiAlias: "kc",
  display: {
    name: "Kilo Code",
    icon: "code",
    color: "#FF6B35",
    textIcon: "KC",
    website: "https://kilocode.ai",
    notice: {
      signupUrl: "https://kilocode.ai",
    },
  },
  category: "oauth",
  hasFree: true,
  transport: {
    baseUrl: "https://api.kilo.ai/api/openrouter/chat/completions",
    headers: {},
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
      hooks: [
        "kilocodeOrg",
      ],
    },
  },
  models: [
    { id: "kilo-auto/free", name: "Auto Free", contextLength: 256000, isFree: true, description: "Default free auto router model on Kilo Code." },
    { id: "stepfun/step-3.7-flash:free", name: "StepFun Step 3.7 Flash (Free)", contextLength: 262144, isFree: true },
    { id: "minimax/minimax-m3:free", name: "MiniMax M3 (Free)", contextLength: 1048576, isFree: true },
    { id: "poolside/laguna-s-2.1:free", name: "Poolside Laguna S 2.1 (Free)", contextLength: 262144, isFree: true },
    { id: "cohere/north-mini-code:free", name: "Cohere North Mini Code (Free)", contextLength: 256000, isFree: true },
    { id: "nvidia/nemotron-3.5-lightning:free", name: "NVIDIA Nemotron 3.5 Lightning (Free)", contextLength: 1000000, isFree: true },
    { id: "openrouter/free", name: "OpenRouter Free Router", contextLength: 200000, isFree: true },
    { id: "kilo-auto/frontier", name: "Auto Frontier", contextLength: 1000000, description: "Highest performance and capability for any task." },
    { id: "kilo-auto/balanced", name: "Auto Balanced", contextLength: 1000000 },
    { id: "kilo-auto/efficient", name: "Auto Efficient", contextLength: 1000000 },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 1000000 },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", contextLength: 1000000 },
    { id: "anthropic/claude-sonnet-4.5", name: "Claude Sonnet 4.5", contextLength: 1000000 },
    { id: "anthropic/claude-opus-4.5", name: "Claude Opus 4.5", contextLength: 1000000 },
    { id: "openai/gpt-5.6-sol", name: "GPT-5.6 Sol", contextLength: 1050000 },
    { id: "openai/gpt-5.6-luna", name: "GPT-5.6 Luna", contextLength: 1050000 },
    { id: "openai/o3", name: "OpenAI o3", contextLength: 200000 },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", contextLength: 1048576 },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash", contextLength: 1048576 },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro", contextLength: 1048576 },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash", contextLength: 1048576 },
    { id: "deepseek/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 07/31", contextLength: 1310720 },
    { id: "deepseek/deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 08/13", contextLength: 1048576 },
    { id: "deepseek/deepseek-chat", name: "DeepSeek Chat", contextLength: 65536 },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek Reasoner", contextLength: 65536 },
  ],
  // Kilo Code proxies the OpenRouter catalog (334 models at time of writing),
  // so the hardcoded list above is only a fallback. Surfacing the full catalog
  // requires a fetcher + passthroughModels, matching how openrouter.js is set up.
  // Without these, only the 8 hardcoded models appear in the combo model picker,
  // hiding dynamic models like cohere/north-mini-code:free and poolside/laguna-m.1:free.
  modelsFetcher: { url: "https://api.kilo.ai/api/gateway/models", type: "openrouter-free" },
  passthroughModels: true,
  oauth: {
    apiBaseUrl: "https://api.kilo.ai",
    initiateUrl: "https://api.kilo.ai/api/device-auth/codes",
    pollUrlBase: "https://api.kilo.ai/api/device-auth/codes",
  },
};
