export default {
  id: "toolnet",
  priority: 1,
  alias: "tn",
  uiAlias: "tn",
  display: {
    name: "ToolNet API",
    icon: "api",
    color: "#673AB7",
    textIcon: "TN",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://inference.poolside.ai/v1/chat/completions",
    validateUrl: "https://inference.poolside.ai/v1/models",
  },
  models: [
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet", upstreamModelId: "poolside/laguna-s-2.1" },
    { id: "claude-3-haiku-20240307", name: "Claude 3 Haiku", upstreamModelId: "poolside/laguna-xs-2.1" },
    { id: "gpt-4o", name: "GPT-4o", upstreamModelId: "poolside/laguna-s-2.1" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini", upstreamModelId: "poolside/laguna-xs-2.1" },
    { id: "gemini-2.5-pro-exp", name: "Gemini 2.5 Pro (Exp)", upstreamModelId: "poolside/laguna-s-2.1" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", upstreamModelId: "poolside/laguna-xs-2.1" },
    { id: "laguna-s-2.1", name: "Laguna S 2.1", upstreamModelId: "poolside/laguna-s-2.1" },
    { id: "laguna-xs-2.1", name: "Laguna XS 2.1", upstreamModelId: "poolside/laguna-xs-2.1" },
    { id: "poolside/laguna-s-2.1", name: "Laguna S 2.1", upstreamModelId: "poolside/laguna-s-2.1" },
    { id: "poolside/laguna-xs-2.1", name: "Laguna XS 2.1", upstreamModelId: "poolside/laguna-xs-2.1" },
  ],
  passthroughModels: true,
};
